# Generated by Django 5.0.6 on 2024-06-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_like_liked_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="liked_post",
            new_name="post",
        ),
    ]
