# Generated by Django 5.0.6 on 2024-06-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_liked_post_like_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post_comment",
            new_name="post",
        ),
    ]
