# Generated by Django 5.0.6 on 2024-06-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_delete_unfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="is_followed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="like",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
    ]
