# Generated by Django 5.0.6 on 2024-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_follow_is_followed_like_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
