# Generated by Django 5.0.6 on 2024-06-20 10:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_media",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.post_image_path
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
