# Generated by Django 4.2 on 2024-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_follow_is_followed_remove_like_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
