# Generated by Django 5.0.6 on 2024-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=63, null=True, unique=True),
        ),
    ]
