# Generated by Django 5.0.6 on 2024-06-18 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_followers",
            field=models.ManyToManyField(
                blank=True, related_name="follow_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_following",
            field=models.ManyToManyField(
                blank=True, related_name="following_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
