# Generated by Django 5.0.6 on 2024-06-20 10:49

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_user_followers_alter_user_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.user_profile_image_path
            ),
        ),
    ]
